baseURL = 'https://ai-digest.derricklin.net'
#baseURL = 'http://localhost:1313/blog'
# baseURL = 'http://localhost:8000'
# title = "Derrick Lin's Blog"
theme = "fujify"

## Change this two to switch between different language
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]


summaryLength = 100 # Custom summary length, add <!--more--> in post file to custom split point

[pagination]
  pagerSize = 10

# googleAnalytics = "UA-000000000-0" # Set your Google Analytics UA here

languageCode = 'en-us'
defaultContentLanguage = 'en'
[languages]
[languages.en]
    languageName = 'English'
    title = "My AI Digest"
    weight = 1

[languages.dl]
    languageName = 'CountryClub'
    title = "Country Club"
    weight = 90

[outputs]
home = ["HTML", "RSS", "JSON"]

# [permalinks]
# post = "/:section/:filename/" # Custom post links, e.g. "/:year/:month/:title/"
# random = "/:year-:month-:day-:filename/"

[params]
author = "dlccyes"                # You can also set author in post front matter individually
# subTitle = "random thoughts"
defaultTheme = "light"              # default theme when first visit (auto|dark|light)
math = true                        # Enable LaTeX math rendering globally

# Source URL of the website, will appear in the footer
sourceURL = "https://github.com/dlccyes/ai-digest"

# Use CloudFlare Workers to accelerate the Google Analytics
# If you are using this please comment the googleAnalytics above
# Check https://github.com/SukkaW/cloudflare-workers-async-google-analytics for more details
# googleAnalyticsTid = "UA-000000000-0"
# googleAnalyticsRoute = "https://*.*.workers.dev/"

# Google AdSense
# The AdSense code will be inserted between the head tags of your site.
# googleAdsense = "0000000000000000"

# Word counter and read time indicator in post metadata
showWordCounter = true
showReadTime = true

# License in the footer
showLicenseInFooter = false

# License at the end of each post
showLicense = false
showToc = true

# Copyright
# copyrightStartYear = "2022"

# Open Graph & Twitter Card variables
# You can also set description and images in post front matter individually
description = "A minimal Hugo theme with nice theme color."
og = "/img/og.png"                                          # This will use the image called og.png in static/img folder

# Posts shown in homepage
mainSections = ["post"]

# Bangumi image chart id
# bgmImageChart = "000000"

# License
license = "CC BY-NC-SA 4.0"
licenseLink = "http://creativecommons.org/licenses/by-nc-sa/4.0/"

# Comments
# utterances, see: https://utteranc.es/
# utterancesRepo = "*/*"
# utterancesIssueTerm = "pathname"

# Disqus, see: https://disqus.com/admin/install/platforms/universalcode/
# disqusShortname = "*********"
# Also use DisqusJS for accessing from Mainland China, see: https://github.com/SukkaW/DisqusJS
# If you want to set multiple api key, see theme's README for more details
# disqusJSApi = "https://*********/"
# disqusJSApikey = "**********"

# custom lazyload placeholder
# 16:9
lazyPlaceholder = "/assets/lazyload/dsrca_loading_480x270.svg"
# 32:9
lazyPlaceholderRow = "/assets/lazyload/dsrca_loading_960x270.svg"
# 8:9
lazyPlaceholderCol = "/assets/lazyload/dsrca_loading_480x540.svg"

# Let images display in full brightness under dark mode
# disableDarkImage = true

[markup]
[markup.goldmark]
duplicateResourceFiles = true # maintain pre-0.123.0 page bundle image behavior
[markup.goldmark.renderer]
unsafe = true # Enable user to embed HTML snippets in Markdown content
[markup.highlight]
codeFences = true

[markup.tableOfContents]
startLevel = 2
endLevel = 3

[taxonomies]
tag = "tags"

[menu]
# [[menu.nav]]
# name = "Home"
# url = "/"
# weight = 2
[[menu.nav]]
name = "Tech"
url = "/tech/"
weight = 10
[[menu.nav]]
name = "Science"
url = "/science/"
weight = 20
[[menu.nav]]
name = "Economics"
url = "/economics/"
weight = 30
[[menu.nav]]
name = "Sports"
url = "/sports/"
weight = 40
[[menu.nav]]
name = "Career"
url = "/career/"
weight = 50

[[menu.link]]
name = "Personal Page"
url = "https://www.derricklin.net"
weight = 1
[[menu.link]]
name = "Blog"
url = "https://blog.derricklin.net"
weight = 2
[[menu.link]]
name = "GitHub"
url = "https://github.com/dlccyes"
weight = 40

[build]
noJSConfigInAssets = true

[security]
enableInlineShortcodes = true
