#!/usr/bin/env python3

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path


def ensure_summary_title(raw_stem: str) -> str:
    stem = raw_stem.strip()
    if not stem:
        raise ValueError("title stem must not be empty")
    if stem.endswith(" Summary"):
        return stem
    return f"{stem} Summary"


def choose_output_path(summary_dir: Path, title: str) -> Path:
    candidate = summary_dir / f"{title}.md"
    if not candidate.exists():
        return candidate
    index = 2
    while True:
        candidate = summary_dir / f"{title} ({index}).md"
        if not candidate.exists():
            return candidate
        index += 1


def escape_yaml_double_quoted(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def resolve_output_dir(repo_root: Path, output_dir: str) -> Path:
    raw = Path(output_dir)
    if raw.is_absolute():
        return raw
    return repo_root / raw


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Create a new Markdown summary file with frontmatter and a generated-by line."
    )
    parser.add_argument("title_stem", help="Title stem before the trailing ' Summary'")
    parser.add_argument(
        "--repo-root",
        required=True,
        help="Path to the repository root that owns the output directory.",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Relative or absolute output directory for the note.",
    )
    parser.add_argument(
        "--tag",
        required=True,
        help="Single tag value to write into the frontmatter tags list.",
    )
    parser.add_argument(
        "--generator",
        default="AI",
        help='Generator label, usually "<tool> with <model>".',
    )
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    summary_dir = resolve_output_dir(repo_root, args.output_dir)
    summary_dir.mkdir(parents=True, exist_ok=True)

    title = ensure_summary_title(args.title_stem)
    output_path = choose_output_path(summary_dir, title)
    now = datetime.now()
    content = (
        "---\n"
        f"date: {now.strftime('%Y-%m-%d')}\n"
        f'title: "{escape_yaml_double_quoted(title)}"\n'
        "tags:\n"
        f"    - {args.tag}\n"
        "---\n\n"
        f"Generated by {args.generator} on [[{now.strftime('%Y%m%d')}]]\n\n"
    )
    output_path.write_text(content, encoding="utf-8")
    print(output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
